//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiderAPIService.Infraestructura.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Posiciones
    {
        public int Id { get; set; }
        public string Usuario { get; set; }
        public Nullable<decimal> Latitud { get; set; }
        public Nullable<decimal> Longitud { get; set; }
        public Nullable<int> Velocidad { get; set; }
        public string Via { get; set; }
        public int IdTipo { get; set; }
        public int idEstado { get; set; }
        public System.DateTime fecha { get; set; }
    
        public virtual Tipo Tipo { get; set; }
        public virtual Estado Estado { get; set; }
    }
}
