//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiderAPIService.Infraestructura.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class siderSQLEntities : DbContext
    {
        public siderSQLEntities()
            : base("name=siderSQLEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Posiciones> Posiciones { get; set; }
        public virtual DbSet<Tipo> Tipo { get; set; }
        public virtual DbSet<Estado> Estado { get; set; }
    
        public virtual ObjectResult<GET_DATOS_POSICIONES_Result> GET_DATOS_POSICIONES(Nullable<decimal> pLatitud, Nullable<decimal> pLongitud, Nullable<int> pDistancia, Nullable<int> pSegundos)
        {
            var pLatitudParameter = pLatitud.HasValue ?
                new ObjectParameter("pLatitud", pLatitud) :
                new ObjectParameter("pLatitud", typeof(decimal));
    
            var pLongitudParameter = pLongitud.HasValue ?
                new ObjectParameter("pLongitud", pLongitud) :
                new ObjectParameter("pLongitud", typeof(decimal));
    
            var pDistanciaParameter = pDistancia.HasValue ?
                new ObjectParameter("pDistancia", pDistancia) :
                new ObjectParameter("pDistancia", typeof(int));
    
            var pSegundosParameter = pSegundos.HasValue ?
                new ObjectParameter("pSegundos", pSegundos) :
                new ObjectParameter("pSegundos", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_DATOS_POSICIONES_Result>("GET_DATOS_POSICIONES", pLatitudParameter, pLongitudParameter, pDistanciaParameter, pSegundosParameter);
        }
    }
}
