//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiderAPIService.Infraestructura.Querys {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SQLQuery {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SQLQuery() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SiderAPIService.Infraestructura.Querys.SQLQuery", typeof(SQLQuery).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT * 
        ///
        ///FROM
        ///
        ///(SELECT Tipo, Latitud, Longitud, Velocidad, Via,
        ///ROUND(ACOS(COS((90 - Latitud) * 3.14159265358979323 / 180) * COS((90 - @pLatitud) * 3.14159265358979323 / 180) + SIN((90 - Latitud)   * 3.14159265358979323 / 180) * SIN((90 - @pLatitud) * 3.14159265358979323 / 180)   * COS((Longitud - @pLongitud) * 3.14159265358979323 / 180)) * 6378137, 2) as DISTANCIA
        ///FROM dbo.Posiciones 
        ///INNER JOIN dbo.Tipo ON dbo.Tipo.Id = dbo.Posiciones.IdTipo ) as DATOS
        ///
        ///WHERE (DISTANCIA &lt;= @pDistancia)
        ///ORDER B [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string GetDatosPosicionesByMetros {
            get {
                return ResourceManager.GetString("GetDatosPosicionesByMetros", resourceCulture);
            }
        }
    }
}
